export const ADD_PRODUCT_TO_KART = "ADD_PRODUCT_TO_KART";
export const REMOVE_PRODUCT_FROM_KART = "REMOVE_PRODUCT_FROM_KART";
export const BUY_PRODUCTS_FROM_KART = "BUY_PRODUCTS_FROM_KART";
export const SET_ACTIVE_MENU_ITEM = "SET_ACTIVE_MENU_ITEM";